#!/usr/bin/env python3
"""
prepare_demo_data.py
====================
Prepares static JSON data files for the Detection Rule Explorer demo page.

Reads:
  data_prep/build_data/rule_versions_{repo}.jsonl   (filtered, clean versions)
  data_prep/rule_lineages_{repo}/*.json              (for commit subjects)
  data_prep/align_data/all_steps_{repo}.jsonl        (d_step per adjacent pair)
  data_prep/align_data/pred_diff_{repo}.jsonl        (predicate-level diff labels)
    → generated by prepare_align_data.py

Writes to <out_dir>/{repo}/:
  index.json            - search index for autocomplete/browse
  {lineage_id}.json     - full timeline for one rule (one per rule)

Usage:
  python prepare_demo_data.py                       # both repos
  python prepare_demo_data.py --repo sigma
  python prepare_demo_data.py --repo ssc
  python prepare_demo_data.py --out-dir /some/path  # override base output dir
"""

import argparse
import json
import logging
import re as _re
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_OUT = HERE.parent / "rule-explorer-data"
MACRO_CACHE_DIR = HERE / "data_prep" / "macro_data" / "macro_cache_by_commit"

# Optional: pgir_align for tree building (gracefully absent if not available)
try:
    sys.path.insert(0, str(HERE / "data_prep" / "align_src"))
    from pgir_align import build_canonical_tree  # type: ignore
    _TREE_AVAILABLE = True
except ImportError:
    _TREE_AVAILABLE = False

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)


# ── category extraction ────────────────────────────────────────────────────

def get_category(rule_canonical: str, repo: str) -> str:
    parts = Path(rule_canonical).parts
    if repo == "sigma":
        if len(parts) > 2 and parts[0] == "rules":
            return parts[1]
        if parts[0].startswith("rules-"):
            return parts[0][len("rules-"):]
        return parts[0] if parts else "other"
    else:  # ssc
        return parts[1] if len(parts) > 2 else (parts[0] if parts else "other")


# ── alignment data loaders ─────────────────────────────────────────────────

def load_steps_index(repo: str) -> dict:
    """Load all_steps_{repo}.jsonl → dict keyed (lineage_id, version_b) → step row.

    Returns empty dict (with warning) if the file does not exist.
    """
    path = HERE / "data_prep" / "align_data" / f"all_steps_{repo}.jsonl"
    if not path.exists():
        log.warning("all_steps_%s.jsonl not found at %s — d_step will be 0 for all steps", repo, path)
        return {}
    index: dict = {}
    with open(path) as fh:
        for line in fh:
            r = json.loads(line)
            index[(r["lineage_id"], r["version_b"])] = r
    log.info("  loaded %d step records from all_steps_%s.jsonl", len(index), repo)
    return index


def load_pgir_index(repo: str) -> dict:
    """Load pgir_{repo}_nonempty.jsonl → dict keyed (lineage_id, version_index).

    Returns empty dict (with warning) if unavailable or pgir_align not importable.
    """
    if not _TREE_AVAILABLE:
        log.warning("pgir_align not importable — tree field will be null for all versions")
        return {}
    path = HERE / "data_prep" / "ir_data" / f"pgir_{repo}_nonempty.jsonl"
    if not path.exists():
        log.warning("pgir_%s_nonempty.jsonl not found — tree field will be null", repo)
        return {}
    index: dict = {}
    with open(path) as fh:
        for line in fh:
            r = json.loads(line)
            index[(r["lineage_id"], r["version_index"])] = r
    log.info("  loaded %d PGIR records for tree building", len(index))
    return index


def tnode_to_compact(node) -> dict:
    """Serialise a TNode to a compact JSON-able dict {t, c?}.

    Operator labels  → "O:AND" / "O:OR" / "O:NOT"
    Predicate labels → "P:field|op|val|CTX:POS/NEG"
    Only stores children key when non-empty (saves ~30% on leaf nodes).
    """
    d: dict = {"t": node.label}
    if node.children:
        d["c"] = [tnode_to_compact(ch) for ch in node.children if ch is not None]
    return d


def build_tree_for_record(pgir_rec: dict) -> dict | None:
    """Build and serialise a compact tree from one PGIR record. Returns None on failure."""
    try:
        root = build_canonical_tree(pgir_rec)
        return tnode_to_compact(root)
    except Exception as exc:
        return None


# ── SSC macro helpers ──────────────────────────────────────────────────────

def build_macro_cache_index() -> dict:
    """Build index: 8-char commit hash prefix → Path to cache JSON file."""
    if not MACRO_CACHE_DIR.exists():
        log.warning("macro_cache_by_commit directory not found at %s", MACRO_CACHE_DIR)
        return {}
    return {f.stem[:8]: f for f in MACRO_CACHE_DIR.iterdir() if f.suffix == ".json"}


_loaded_macro_caches: dict = {}  # 8-char hash → macro dict (loaded lazily)


def get_macros_for_commit(hash8: str, macro_idx: dict) -> dict:
    """Return macro dict for a commit (keyed by macro name). Empty if unavailable."""
    if hash8 in _loaded_macro_caches:
        return _loaded_macro_caches[hash8]
    f = macro_idx.get(hash8)
    result: dict = {}
    if f:
        try:
            result = json.loads(f.read_text()) or {}
        except Exception:
            pass
    _loaded_macro_caches[hash8] = result
    return result


def extract_macros_for_version(detection: str, hash8: str, macro_idx: dict) -> dict | None:
    """Extract backtick macro names from an SPL detection block, look them up in the
    macro cache for the given commit, and return {name: expansion} or None if nothing found.
    """
    if not detection:
        return None
    # Backtick macros: `macroname` or `macroname(args)`
    names = list(dict.fromkeys(_re.findall(r'`([a-zA-Z0-9_]+)(?:\([^)]*\))?`', detection)))
    if not names:
        return None
    cache = get_macros_for_commit(hash8, macro_idx)
    found = {name: cache[name] for name in names if name in cache}
    return found or None


def load_pred_diff_index(repo: str) -> dict:
    """Load pred_diff_{repo}.jsonl → dict keyed (lineage_id, version_b) → diff row.

    Returns empty dict (with warning) if the file does not exist — run
    prepare_align_data.py first.
    """
    path = HERE / "data_prep" / "align_data" / f"pred_diff_{repo}.jsonl"
    if not path.exists():
        log.warning(
            "pred_diff_%s.jsonl not found at %s — no predicate diff in output. "
            "Run prepare_align_data.py first.",
            repo, path,
        )
        return {}
    index: dict = {}
    with open(path) as fh:
        for line in fh:
            r = json.loads(line)
            index[(r["lineage_id"], r["version_b"])] = r
    log.info("  loaded %d pred_diff records from pred_diff_%s.jsonl", len(index), repo)
    return index


# ── per-repo pipeline ──────────────────────────────────────────────────────

def process_repo(repo: str, out_base: Path) -> None:
    lineages_dir  = HERE / "data_prep" / f"rule_lineages_{repo}"
    versions_file = HERE / "data_prep" / "build_data" / f"rule_versions_{repo}.jsonl"
    out_dir       = out_base / repo
    out_dir.mkdir(parents=True, exist_ok=True)

    # Step 1: commit_hash → commit_subject from raw lineage files
    log.info("[%s] Building commit subject map...", repo)
    commit_subjects: dict[str, str] = {}
    for f in sorted(lineages_dir.glob("*.json")):
        try:
            data = json.loads(f.read_text())
        except Exception:
            continue
        for c in data.get("commits", []):
            h = c.get("commit_hash")
            s = c.get("commit_subject") or ""
            if h and h not in commit_subjects:
                commit_subjects[h] = s
    log.info("  %d commit subjects loaded", len(commit_subjects))

    # Step 2: load alignment data, PGIR trees, and macro index (SSC only)
    log.info("[%s] Loading alignment data...", repo)
    steps_idx     = load_steps_index(repo)
    pred_diff_idx = load_pred_diff_index(repo)
    pgir_idx      = load_pgir_index(repo)

    macro_idx: dict = {}
    if repo == "ssc":
        log.info("[%s] Building macro cache index...", repo)
        macro_idx = build_macro_cache_index()
        log.info("  %d macro cache files indexed", len(macro_idx))

    # Step 3: read versioned records, group by lineage_id
    log.info("[%s] Reading rule versions...", repo)
    lineages: dict[str, list] = defaultdict(list)
    with open(versions_file) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            lineages[rec["lineage_id"]].append(rec)
    log.info(
        "  %d lineages, %d total versions",
        len(lineages), sum(len(v) for v in lineages.values()),
    )

    # Step 4: write per-rule JSON files and accumulate index
    log.info("[%s] Writing rule files...", repo)
    index = []
    missing_align_warnings = []
    no_pgir_step_count = 0   # versions where step had no all_steps entry (expected for pre-PGIR versions)

    for lineage_id, versions in sorted(lineages.items()):
        versions.sort(key=lambda v: v["version_index"])

        rule_canonical = versions[0]["rule_canonical"]
        display_name   = Path(rule_canonical).stem

        out_versions = []
        _MACRO_UNSET = object()       # sentinel: first iteration always writes macros
        last_macros = _MACRO_UNSET
        for i, v in enumerate(versions):
            vi        = v["version_index"]
            detection = v.get("detection_block") or ""

            # d_step from alignment (replaces SequenceMatcher delta)
            delta = 0.0
            align_field = None

            if i > 0:
                step = steps_idx.get((lineage_id, vi))
                if step is not None:
                    delta = step["d_step"]
                    # Build align field: always include counts; add predicate
                    # labels only for non-noop steps where we have pred_diff data.
                    if step["is_noop"]:
                        # No-op: just store matched_count so UI can say "N unchanged"
                        align_field = {
                            "matched": [],   # empty — no diff to show
                            "nc": step["align_summary"].get("matched_count", 0),
                        }
                    else:
                        pd = pred_diff_idx.get((lineage_id, vi))
                        if pd is not None:
                            align_field = {
                                "counts":   pd["counts"],
                                "changed":  pd["changed"],
                                "matched":  pd["matched"],   # unchanged predicate labels
                                "deleted":  pd["deleted"],
                                "inserted": pd["inserted"],
                            }
                        else:
                            # Non-noop but no pred_diff — unexpected, log it
                            msg = (
                                f"repo={repo} lineage={lineage_id} vi={vi}: "
                                "non-noop step has no pred_diff record"
                            )
                            missing_align_warnings.append(msg)
                            # Still provide counts from steps_idx; no labels available
                            cc = step.get("change_counts", {})
                            align_field = {
                                "counts": {
                                    "value_shift": cc.get("pred_value_shift", 0),
                                    "op_shift":    cc.get("pred_op_shift",    0),
                                    "field_shift": cc.get("pred_field_shift", 0),
                                    "inserted":    cc.get("pred_insertion",   0),
                                    "deleted":     cc.get("pred_deletion",    0),
                                },
                                "matched":  [],
                                "changed":  [],
                                "deleted":  [],
                                "inserted": [],
                                "nc": step["align_summary"].get("matched_count", 0),
                            }
                else:
                    # No alignment step for this version: the version likely
                    # pre-dates PGIR coverage (e.g. early SSC versions using
                    # generating SPL that the IR stage could not parse).
                    # delta stays 0.0, align stays None — no action needed.
                    no_pgir_step_count += 1

            # ── tree field ──────────────────────────────────────────
            # Store compact boolean-AST tree for:
            #   v1 (always, so frontend can render it standalone)
            #   any non-noop version (tree changed here)
            # Noop versions and no-PGIR versions → null (inherit previous tree).
            tree_field = None
            is_noop_step = (
                i > 0
                and steps_idx.get((lineage_id, vi), {}).get("is_noop", True)
            )
            needs_tree = (i == 0) or (not is_noop_step)
            if needs_tree:
                pgir_rec = pgir_idx.get((lineage_id, vi))
                if pgir_rec is not None:
                    tree_field = build_tree_for_record(pgir_rec)

            # ── macros field (SSC only) ─────────────────────────────
            # Store macro definitions whenever they change (covers cache
            # first appearing, definitions evolving, or macros disappearing).
            # Unchanged versions get null → frontend walks backwards to find
            # the most recently stored macros (same walk-back logic as tree).
            macros_field = None
            if repo == "ssc":
                current_macros = extract_macros_for_version(
                    detection, v["commit_hash"][:8], macro_idx
                )
                if current_macros != last_macros:
                    macros_field = current_macros   # may be None if cache empty
                    last_macros = current_macros

            out_versions.append({
                "vi":        vi,
                "date":      v["commit_date"],
                "hash":      v["commit_hash"][:8],
                "subject":   commit_subjects.get(v["commit_hash"], ""),
                "detection": detection,
                "delta":     round(delta, 4),
                "align":     align_field,
                "tree":      tree_field,
                "macros":    macros_field,
            })

        (out_dir / f"{lineage_id}.json").write_text(
            json.dumps({
                "lineage_id":     lineage_id,
                "display_name":   display_name,
                "rule_canonical": rule_canonical,
                "repo":           repo,
                "versions":       out_versions,
            }, separators=(",", ":"), ensure_ascii=False)
        )

        max_delta = max((v["delta"] for v in out_versions), default=0.0)
        index.append({
            "id":        lineage_id,
            "name":      display_name,
            "path":      rule_canonical,
            "n":         len(out_versions),
            "from":      out_versions[0]["date"][:10],
            "to":        out_versions[-1]["date"][:10],
            "max_delta": round(max_delta, 4),
            "cat":       get_category(rule_canonical, repo),
        })

    if missing_align_warnings:
        log.warning(
            "[%s] %d unexpected missing alignment entries:", repo, len(missing_align_warnings)
        )
        for msg in missing_align_warnings:
            log.warning("  %s", msg)

    if no_pgir_step_count:
        log.info(
            "[%s] %d version steps have no PGIR coverage (pre-PGIR or IR-parse failure) "
            "— delta=0 / align=null for those steps",
            repo, no_pgir_step_count,
        )

    index.sort(key=lambda x: x["name"])
    (out_dir / "index.json").write_text(
        json.dumps(index, separators=(",", ":"), ensure_ascii=False)
    )
    index_kb = (out_dir / "index.json").stat().st_size // 1024
    log.info("[%s] Done. %d rules + index.json (%d KB) → %s", repo, len(index), index_kb, out_dir)


# ── entry point ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo",    choices=["sigma", "ssc", "both"], default="both",
                        help="Which repo to process (default: both)")
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT,
                        help=f"Base output directory (default: {DEFAULT_OUT})")
    args = parser.parse_args()

    repos = ["sigma", "ssc"] if args.repo == "both" else [args.repo]
    had_warnings = False
    for repo in repos:
        process_repo(repo, args.out_dir)

    if had_warnings:
        log.warning("Finished with warnings — check output above.")
        sys.exit(1)
    else:
        log.info("All done.")


if __name__ == "__main__":
    main()
